services:
  traefik:
    image: 'traefik:latest'
    command:
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.web.address=:80'
    ports:
      - '81:80'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'

  vue-admin:
    container_name: vue-admin
    command: --spa --port 8082
    build:
      context: ..
      dockerfile: ./docker/vue-damin.Dockerfile
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.vue-admin.rule=Host(`vue-admin.localhost`)'
      - 'traefik.http.services.vue-admin.loadbalancer.server.port=8082' # port inside of trfk-vue which should be used